### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-ccm#142]
See for example [byo_build_tests_dtest/70/consoleFull](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/70/consoleFull):
```
18:31:43 /jenkins/workspace/scylla-master/manual-and-scheduled-tests/byo_build_tests_dtest/scylla-ccm/ccmlib/scylla_node.py:601: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
18:31:43   data = yaml.load(f)
18:31:43 /jenkins/workspace/scylla-master/manual-and-scheduled-tests/byo_build_tests_dtest/scylla-ccm/ccmlib/scylla_node.py:324: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```

Please read [https://msg.pyyaml.org/load](https://msg.pyyaml.org/load) for full details.

**Comment by bhalevy** [comment]
879184f8aa09b43a493a17495cf41354a8fb23ab was dequeued:
```
05:02:22  
05:02:22  ======================================================================
05:02:22  ERROR: removing_default_ttl_does_not_affect_existing_rows_test (ttl_test.TestTTL)
05:02:22  ----------------------------------------------------------------------
05:02:22  Traceback (most recent call last):
05:02:22    File "/jenkins/workspace/scylla-master/next/scylla-dtest/ttl_test.py", line 149, in removing_default_ttl_does_not_affect_existing_rows_test
05:02:22      self.prepare(default_time_to_live=1)
05:02:22    File "/jenkins/workspace/scylla-master/next/scylla-dtest/ttl_test.py", line 34, in prepare
05:02:22      self.cluster.populate(nodes).start()
05:02:22    File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/cluster.py", line 199, in populate
05:02:22      binary_interface=binary)
05:02:22    File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/scylla_cluster.py", line 55, in create_node
05:02:22      initial_token, save, binary_interface)
05:02:22    File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/scylla_node.py", line 67, in __init__
05:02:22      initial_token, save, binary_interface)
05:02:22    File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/node.py", line 110, in __init__
05:02:22      self.import_config_files()
05:02:22    File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/scylla_node.py", line 528, in import_config_files
05:02:22      self.__update_yaml()
05:02:22    File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/scylla_node.py", line 614, in __update_yaml
05:02:22      data = yaml.full_load(f)
05:02:22  AttributeError: 'module' object has no attribute 'full_load'
```
