### ISSUE TITLE
CCM fails to download relocatable packages - patchelf: std::bad_alloc

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-ccm#244]
CCM branch: master (up to date)
Scylla branch: master
Packages attempted: Various packages between 2020-06 and 2020--08

When trying to download a new scylla relocatable package (tried a few different packages) I receive the following exception after a few minutes with no error messages:
```
Relocatable package format version 2 detected.
Relocatable package format version 2 detected.
Relocatable package format version 2 detected.
patchelf: std::bad_alloc
E
======================================================================
ERROR: test_backup_task_progress (manager_backup_tests.TestScyllaMgmtBackup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomib/projects/scylla-dtest/dtest.py", line 619, in setUp
    self.cluster = self._get_cluster(version=self.cassandra_version)
  File "/home/shlomib/projects/scylla-dtest/dtest.py", line 439, in _get_cluster
    cluster = ScyllaCluster(self.test_path, name, cassandra_version=scylla_version,
  File "/home/shlomib/projects/scylla-ccm/ccmlib/scylla_cluster.py", line 40, in __init__
    super(ScyllaCluster, self).__init__(path, name, partitioner,
  File "/home/shlomib/projects/scylla-ccm/ccmlib/cluster.py", line 62, in __init__
    dir, v = self.load_from_repository(version, verbose)
  File "/home/shlomib/projects/scylla-ccm/ccmlib/scylla_cluster.py", line 60, in load_from_repository
    install_dir, version = scylla_repository.setup(version, verbose)
  File "/home/shlomib/projects/scylla-ccm/ccmlib/scylla_repository.py", line 71, in setup
    run_scylla_install_script(os.path.join(
  File "/home/shlomib/projects/scylla-ccm/ccmlib/scylla_repository.py", line 243, in run_scylla_install_script
    run('''{0}/install.sh --root {1} --prefix {1} --prefix /opt/scylladb --nonroot'''.format(
  File "/home/shlomib/projects/scylla-ccm/ccmlib/scylla_repository.py", line 32, in run
    subprocess.check_call(['bash', '-c', cmd], cwd=cwd,
  File "/home/shlomib/.pyenv/versions/3.8.3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '-c', '/home/shlomib/.ccm/scylla-repository/unstable/master/2020-08-29T22_24_05Z/scylla-core-package/install.sh --root /home/shlomib/.ccm/scylla-repository/unstable/master/2020-08-29T22_24_05Z/scylla --prefix /home/shlomib/.ccm/scylla-repository/unstable/master/2020-08-29T22_24_05Z/scylla --prefix /opt/scylladb --nonroot']' returned non-zero exit status 1.
```

**Comment by avikivity** [comment]
Which package did you try?

**Comment by fruch** [comment]
@ShlomiBalalis, I've been able to download and run the same version 

try clearing that version from  `~/.ccm/scylla-repository`
```
rm ~/.ccm/scylla-repository/unstable/master/2020-08-29T22_24_05Z/
```

and download it again:
```
ccm create scylla-driver-temp -n 1 --scylla --version unstable/master:2020-08-29T22:24:05Z
ccm start
ccm node1 showlog
```

you can also use this snippet https://gist.github.com/fruch/cc6e8f56c27048780c1ef2cf45c199d3 to download a bit faster with the aws cli.

**Comment by ShlomiBalalis** [comment]
I tried to restart my machine and now the download works fine, so whatever the issue was, it no longer happens.
Just for the record, I tried downloading:
```
2020-08-29T22:24:05Z
2020-08-19T11:32:30Z
2020-08-15T23:54:15Z
2020-08-01T12:53:22Z
2020-06-24T19:18:25Z
```
