### ISSUE TITLE
"ccm create" fails with "-v release:2021.1.16"

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla-ccm#413]
When executing `ccm create ccm_1 -i 127.0.1.  -n 1  --scylla  -v release:2021.1.16`, ccm fails with:

```
S3 download: scylla-enterprise-x86_64-unified-package-2021.1.16.0.20221022.3224379e7.tar.gz100%|██████████| 1.12G/1.12G [00:35<00:00, 31.3MB/s]
Extracting /tmp/ccm-3_kulzdn.tar.gz (https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2021.1/scylla-enterprise-x86_64-unified-package-2021.1.16.0.20221022.3224379e7.tar.gz, /tmp/tmpaf6m1de_) as version release/2021.1.16 ...
Relocatable package format version 2 detected.
Usage: install.sh [options]

Options:
  --root /path/to/root     alternative install root (default /)
  --prefix /prefix         directory prefix (default /usr)
  --python3 /opt/python3   path of the python3 interpreter relative to install root (default /opt/scylladb/python3/bin/python3)
  --housekeeping           enable housekeeping service
  --nonroot                install Scylla without required root priviledge
  --sysconfdir /etc/sysconfig   specify sysconfig directory name
  --help                   this helpful message
Traceback (most recent call last):
  File "/home/piotrgrabowski/.local/bin/ccm", line 75, in <module>
    cmd.run()
  File "/home/piotrgrabowski/.local/lib/python3.11/site-packages/ccmlib/cmds/cluster_cmds.py", line 223, in run
    cluster = ScyllaCluster(self.path, self.name, install_dir=self.options.install_dir,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piotrgrabowski/.local/lib/python3.11/site-packages/ccmlib/scylla_cluster.py", line 50, in __init__
    super(ScyllaCluster, self).__init__(path, name, partitioner,
  File "/home/piotrgrabowski/.local/lib/python3.11/site-packages/ccmlib/cluster.py", line 71, in __init__
    dir, v = self.load_from_repository(version, verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piotrgrabowski/.local/lib/python3.11/site-packages/ccmlib/scylla_cluster.py", line 71, in load_from_repository
    install_dir, version = scylla_repository.setup(version, verbose)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piotrgrabowski/.local/lib/python3.11/site-packages/ccmlib/scylla_repository.py", line 312, in setup
    run_scylla_unified_install_script(**args)
  File "/home/piotrgrabowski/.local/lib/python3.11/site-packages/ccmlib/scylla_repository.py", line 522, in run_scylla_unified_install_script
    run('''{0}/install.sh --prefix {1} --nonroot{2}'''.format(
  File "/home/piotrgrabowski/.local/lib/python3.11/site-packages/ccmlib/scylla_repository.py", line 47, in run
    subprocess.check_call(['bash', '-c', cmd], cwd=cwd,
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '-c', '/home/piotrgrabowski/.ccm/scylla-repository/release/2021.1.16/scylla-core-package/install.sh --prefix /home/piotrgrabowski/.ccm/scylla-repository/release/2021.1.16 --nonroot --supervisor']' returned non-zero exit status 1.
```

I think that one of the problems is a `--supervisor` flag passed to `install.sh` - it looks like 2021.1.16 does not support it, so `install.sh` fails.

**Comment by fruch** [comment]
@avelanarius 

This is newly introduced unified package, 
too bad it's not unified across all branches and versions.

I'll look into tomorrow, or next week.

is it blocking something urgent ?
