### ISSUE TITLE
"ccm create" fail with error:  Command '['bash', '-c', '/home/artsiom/.ccm/scylla-repository/unstable/branch-5.0/latest/scylla-core-package/install.sh --prefix /home/artsiom/.ccm/scylla-repository/unstable/branch-5.0/latest --nonroot --supervisor']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by temichus** [scylladb/scylla-ccm#429]
"ccm create command " fail with error:  Command '['bash', '-c', '/home/artsiom/.ccm/scylla-repository/unstable/branch-5.0/latest/scylla-core-package/install.sh --prefix /home/artsiom/.ccm/scylla-repository/unstable/branch-5.0/latest --nonroot --supervisor']' returned non-zero exit status 1.

full output
```
ccm create --scylla -v unstable/branch-5.0:latest -n 2 tes4
S3 download: scylla-x86_64-unified-package-5.0.9.0.20230125.94b8baa79.tar.gz100%|██████████| 453M/453M [00:20<00:00, 21.8MB/s] 
Extracting /tmp/ccm-bv6m4p53.tar.gz (http://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-5.0/relocatable/2023-01-25T02:52:16Z/scylla-x86_64-unified-package-5.0.9.0.20230125.94b8baa79.tar.gz, /tmp/tmpo8b9q434) as version unstable/branch-5.0/latest ...
Relocatable package format version 2 detected.
./install.sh: line 458: /home/artsiom/.config/systemd/user/scylla-server.service.d/nonroot.conf: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 4, in <module>
    __import__('pkg_resources').run_script('ccm==2.0.5', 'ccm')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/ccm-2.0.5-py3.8.egg/EGG-INFO/scripts/ccm", line 75, in <module>
    cmd.run()
  File "/usr/local/lib/python3.8/dist-packages/ccm-2.0.5-py3.8.egg/ccmlib/cmds/cluster_cmds.py", line 223, in run
    cluster = ScyllaCluster(self.path, [self.name](http://self.name/), install_dir=self.options.install_dir,
  File "/usr/local/lib/python3.8/dist-packages/ccm-2.0.5-py3.8.egg/ccmlib/scylla_cluster.py", line 50, in __init__
    super(ScyllaCluster, self).__init__(path, name, partitioner,
  File "/usr/local/lib/python3.8/dist-packages/ccm-2.0.5-py3.8.egg/ccmlib/cluster.py", line 71, in __init__
    dir, v = self.load_from_repository(version, verbose)
  File "/usr/local/lib/python3.8/dist-packages/ccm-2.0.5-py3.8.egg/ccmlib/scylla_cluster.py", line 71, in load_from_repository
    install_dir, version = scylla_repository.setup(version, verbose)
  File "/usr/local/lib/python3.8/dist-packages/ccm-2.0.5-py3.8.egg/ccmlib/scylla_repository.py", line 314, in setup
    run_scylla_unified_install_script(**args)
  File "/usr/local/lib/python3.8/dist-packages/ccm-2.0.5-py3.8.egg/ccmlib/scylla_repository.py", line 524, in run_scylla_unified_install_script
    run('''{0}/install.sh --prefix {1} --nonroot{2}'''.format(
  File "/usr/local/lib/python3.8/dist-packages/ccm-2.0.5-py3.8.egg/ccmlib/scylla_repository.py", line 47, in run
    subprocess.check_call(['bash', '-c', cmd], cwd=cwd,
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '-c', '/home/artsiom/.ccm/scylla-repository/unstable/branch-5.0/latest/scylla-core-package/install.sh --prefix /home/artsiom/.ccm/scylla-repository/unstable/branch-5.0/latest --nonroot --supervisor']' returned non-zero exit status 1.
```

workaround:
delete  /home/artsiom/.config/systemd/user/scylla-server.service.d/nonroot.conf file

```
$ stat /home/artsiom/.config/systemd/user/scylla-server.service.d/nonroot.conf
  File: /home/artsiom/.config/systemd/user/scylla-server.service.d/nonroot.conf -> ../../../../.ccm/scylla-repository/unstable/master/202001250259/scylla/etc/systemd/system/scylla-server.service.d/nonroot.conf
  Size: 126       	Blocks: 8          IO Block: 4096   symbolic link
Device: 3fh/63d	Inode: 8782500     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1001/ artsiom)   Gid: ( 1001/ artsiom)
Access: 2023-01-09 12:32:03.668594981 +0100
Modify: 2023-01-09 12:32:03.668594981 +0100
Change: 2023-01-09 12:32:03.668594981 +0100
 Birth: -
$ cat /home/artsiom/.config/systemd/user/scylla-server.service.d/nonroot.conf
cat: /home/artsiom/.config/systemd/user/scylla-server.service.d/nonroot.conf: No such file or directory

```

cc @fruch

**Comment by fruch** [comment]
This one was cause by a bug in scylla install.sh, and was fixed long ago
