### ISSUE TITLE
Using scylla-ccm without a local Scylla build

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla-ccm#438]
How do I use `scylla-ccm` without building a local Scylla and passing a path to `build/release/scylla`?

I tried using the docker image flag, but it fails with a timeout error:
```bash
(virenv) [username@usernamelap]~/code/test/scylla-ccm$ ccm create docker_test -n 3 --scylla --docker-image=scylladb/scylla
Current cluster is now: docker_test
(virenv) [username@usernamelap]~/code/test/scylla-ccm$ ccm status
Cluster: 'docker_test'
----------------------
node1: DOWN (Not initialized)
node2: DOWN (Not initialized)
node3: DOWN (Not initialized)
(virenv) [username@usernamelap]~/code/test/scylla-ccm$ ccm start
Traceback (most recent call last):
  File "/home/username/code/test/scylla-ccm/virenv/bin/ccm", line 4, in <module>
    __import__('pkg_resources').run_script('ccm==2.0.5', 'ccm')
  File "/home/username/code/test/scylla-ccm/virenv/lib64/python3.11/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/username/code/test/scylla-ccm/virenv/lib64/python3.11/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/home/username/code/test/scylla-ccm/virenv/lib/python3.11/site-packages/ccm-2.0.5-py3.11.egg/EGG-INFO/scripts/ccm", line 75, in <module>
    cmd.run()
  File "/home/username/code/test/scylla-ccm/virenv/lib64/python3.11/site-packages/ccm-2.0.5-py3.11.egg/ccmlib/cmds/cluster_cmds.py", line 687, in run
    if self.cluster.start(no_wait=self.options.no_wait,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/code/test/scylla-ccm/virenv/lib64/python3.11/site-packages/ccm-2.0.5-py3.11.egg/ccmlib/scylla_cluster.py", line 160, in start
    started = self.start_nodes(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/code/test/scylla-ccm/virenv/lib64/python3.11/site-packages/ccm-2.0.5-py3.11.egg/ccmlib/scylla_cluster.py", line 128, in start_nodes
    p = node.start(update_pid=False, jvm_args=jvm_args,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/code/test/scylla-ccm/virenv/lib64/python3.11/site-packages/ccm-2.0.5-py3.11.egg/ccmlib/scylla_node.py", line 642, in start
    scylla_process = self._start_scylla(args, marks, update_pid,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/code/test/scylla-ccm/virenv/lib64/python3.11/site-packages/ccm-2.0.5-py3.11.egg/ccmlib/scylla_docker_cluster.py", line 322, in _start_scylla
    self.create_docker(args)
  File "/home/username/code/test/scylla-ccm/virenv/lib64/python3.11/site-packages/ccm-2.0.5-py3.11.egg/ccmlib/scylla_docker_cluster.py", line 183, in create_docker
    self.watch_log_for("supervisord started with", from_mark=0, timeout=10)
  File "/home/username/code/test/scylla-ccm/virenv/lib64/python3.11/site-packages/ccm-2.0.5-py3.11.egg/ccmlib/node.py", line 492, in watch_log_for
    raise TimeoutError(time.strftime("%d %b %Y %H:%M:%S", time.gmtime()) + " [" + self.name + "] Missing: " + str(
ccmlib.node.TimeoutError: 14 Mar 2023 16:37:34 [node1] Missing: ['supervisord started with']:
Emulate Docker CLI using podman. Create /etc/conta.....
See system.log for remainder
```
`ccm create/start --help` doesn't have anything about timeouts

I tried it on `next` and `branch-5.2`.

I also saw that there's an option to specify a package `.tar.gz` (maybe even using a link without downloading (?)), but where do I get these packages from?

I can open a PR to add instructions to the README, but I would need some pointers.

**Comment by fruch** [comment]
the docker based ccm, isn't really working it was part of 2020 hackathon, but it soon after was broken. and it's not operational since then

you can checkout the files in scripts directory, for examples on how to pull different versions

and update to the README would be great, we mostly update the information in dtest (the main user of ccm), and the docs/readme in this repo wasn't updated since it was forked...

**Comment by nyh** [comment]
> Ahh looking through the issues I see it's possible to do it like this:
> 
> ```
> ccm create vtest2 -n 3 --scylla -v release:2022.2.1
> ```
> 
> I will open a PR to add this to the README

Nice. I should one day add such a feature also to scylla.git's test/cql-pytest/run, to run a chosen Scylla version in docker instead of self-compiled build/*/scylla.

**Comment by nyh** [comment]
> Anyhow we are using this in testing for a long long while now, i.e. calling a version by name and finding the artifact needed (docker, RPM, DEB, AMI, or unified relocatable package) it's a bit tricky and can change from time to time, directory structures and filenames, but you have a reference for it CCM :\

Good idea, getting a "relocatable package" (tar of executable and libraries) is much better than a full-blown docker with a lot of other stuff (like JMX) that I don't want.
