### ISSUE TITLE
Fix compatibility with Python 3.12

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla-ccm#537]
In https://github.com/scylladb/java-driver we run scylla-ccm for integration tests in GitHub Actions. Recently, GitHub Actions switched to using Python 3.12 by default and CCM fails to start with the following error:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0/x64/bin/ccm", line 7, in <module>
    from ccmlib.cmds import command, cluster_cmds, node_cmds
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/ccmlib/cmds/command.py", line 6, in <module>
    from ccmlib.cluster_factory import ClusterFactory
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/ccmlib/cluster_factory.py", line 5, in <module>
    from ccmlib import common, repository
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/ccmlib/repository.py", line 15, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

`distutils` was removed in Python 3.12.

**Comment by avelanarius** [comment]
(For now I'll probably resort to using Python 3.11 in that repo)

**Comment by fruch** [comment]
This is weird, since I've tested the python driver with 3.12 (but it was a release candidate)

**Comment by roydahan** [comment]
Why didn't we just set it to use with python 3.11 for now?
At least so the CI won't be broken for so long.

**Comment by fruch** [comment]
> Why didn't we just set it to use with python 3.11 for now?
> At least so the CI won't be broken for so long.
> 
> 

Which CI ?

**Comment by roydahan** [comment]
java-driver CI.

Can you please check this PR?
https://github.com/scylladb/java-driver/pull/269
